- name: "Download Go v{{ go_version}}"
  get_url:
    url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go.tar.gz"
  tags: &tags_for_go_tasks  "go"

- name: Extract Go archive
  ansible.builtin.unarchive:
    src: "/tmp/go.tar.gz"
    dest: "/usr/local"
    remote_src: true
  tags: *tags_for_go_tasks

- name: Ensure GOPATH directory exists
  ansible.builtin.file:
    path: "{{ user_home_path }}/go"
    state: directory
  tags: *tags_for_go_tasks
