- name: "Install Lazygit v{{ lazygit_version }}"
  command: "{{ item }}"
  loop:
    - 'curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"'
    - tar xf lazygit.tar.gz lazygit
    - sudo install lazygit /usr/local/bin
    - rm  lazygit
    - rm  lazygit.tar.gz
  tags: "lazygit"
