- name: Install snap
  apt:
    name: snapd
    state: latest
  tags: [ "packages" , "snap" ]

- name: Install snap packages
  command: "snap install {{ item }} "
  loop: 
    - slack
    - zoom-client
    - spotify
    - remmina
    - intellij-idea-ultimate --classic
    - chromium
    - ngrok
    - helm --classic
  tags: [ "packages", "snap" ]
