- name: Install ZSH
  apt: name=zsh
    
- name: Set Zsh as the default shell
  user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: Check that the .oh-my-zsh file exists
  stat:
    path: "{{ user_home_path }}/.oh-my-zsh"
  register: oh_my_stats

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: oh_my_stats.stat.exists == False
  become: true
  become_user: "{{ user }}"
