export EDITOR='vim'
export VISUAL='vim'
export TERM="xterm-256color"
export ZSH="$HOME/.oh-my-zsh"
export PATH="/usr/local/share/nvim/bin:$PATH"
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
export ANSIBLE_LOCALHOST_WARNING=False
export DOCKER_BUILDKIT=1
export KUBE_EDITOR=nvim

bindkey -M viins 'jk' vi-cmd-mode

ZSH_THEME="robbyrussell"
#plugins=(git)
plugins=(vi-mode)

source $ZSH/oh-my-zsh.sh

source <(kubectl completion zsh)  
kubectl completion zsh > "${fpath[1]}/_kubectl"

# Local/private machine-specific settings belong here.
# Example: aliases, cloud hosts, Android SDK path, private domains.
[ -f "$HOME/.zshrc_local" ] && source "$HOME/.zshrc_local"

#aliases
alias vim="nvim"
export PATH=$HOME/.cargo/bin:$PATH


#keybinds
bindkey -s '^N' 'nvim .\n'
# bindkey -s ^f "tmux-sessionizer\n"
# bindkey -s N "tmux switch -n\n"
# bindkey -s L "tmux switch -l\n"
#bindkey -s ^. "tmux-sessionizer forward\n"
# bindkey -s '^s' 'tmux-sessionizer back\n'
# bindkey -s '^d' 'tmux-sessionizer forward\n'

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then . "$HOME/.nix-profile/etc/profile.d/nix.sh"; fi # added by Nix installer

# source <(kubeclt completion bash)

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

# opencode
[ -d "$HOME/.opencode/bin" ] && export PATH="$HOME/.opencode/bin:$PATH"
